### ISSUE TITLE
Bluetooth error messages

### ISSUE THREAD

**Issue by 1adam12** [HvB/UsbGps4Droid#2]
THANK YOU for this terrific software. Works great on my WM8650 Froyo tablet. Have posted my success on HcH Tech Know site.
Along with your next release I would like confusing bluetooh messages updated for usb gps. More important is seeing constillation of sats and signal levels and compass bearing.  If this apk could drive GPS Essentials complete functions that would be teriffic.

**Comment by 1adam12** [comment]
I use the Silicon Labs device with cp210x.ko driver and it now occurs to me that it is not supporting constillation and signal levels.

**Comment by HvB** [comment]
The app is adapted from blueGPS4Droid (bluetooth GPS dor android), Since I don't have any USB GPS, I can't test or validate modifications. So it's not actually a priority for me. I will modify the messages when I will have time.

For the sat constellation and signal levels, it's not easily feasible with the actual state of Android API. So don't expect to have it for the moment.
