### ISSUE TITLE
Compatible devices?

### ISSUE THREAD

**Issue by edgararroyo** [HvB/UsbGps4Droid#4]
Does someone have the most compatible devices for this project?  A list of reported working ones in ICS?  Do they need to be USB -> Serial  (i.e. PL2303) or straight USB?

Sorry for my ignorance, couldn't find a better place to post this...

**Comment by HvB** [comment]
Actually it needs some tty device to read the NMA sentences, so it's possible you need a pl2303 module if your android device don't create the tty itsef.

You can perhaps use this thread in XDA to obtain more information and ask questions: [Can someone support the USB GPS](http://forum.xda-developers.com/showthread.php?t=1143329).

I don't have any usb or serial GPS myself, so I'm little short of informations about what to do in order to obtain the tty.
I've contacted several GPS constructors, hopping that one or another could support this work by giving me a free sample, but no luck till now...

Herbert

**Comment by edgararroyo** [comment]
Ok, thank you very much.  I have Kernel 3.0.8+ and I am looking like crazy for any PL2303 type of adapter I can use, even if I have to cut and solder...
Thanks!

Date: Tue, 28 Aug 2012 10:55:16 -0700
